### ISSUE TITLE
Syntax error in configure

### ISSUE THREAD

**Issue by re1** [Lixxia/i3lock#11]
After running `autoreconf -fi` while running `../configure` I am getting the following error.

```
checking for library containing pam_authenticate... -lpam
checking for library containing iconv_open... none required
../configure: line 6360: syntax error near unexpected token `XCB,'
../configure: line 6360: `PKG_CHECK_MODULES(XCB, xcb xcb-xkb xcb-randr)'
```
I tried to install as many packages as possible from the official Arch Linux repository including:

- xcb-proto
- xcb-util
- xcb-util-image
- xcb-util-keysyms
- xcb-util-renderutil
- xcb-util-wm, xcb-util-xrm
- libev
- libxinerama
- libxkbcommon
- libxkbcommon-x11

---

**OS**: Arch Linux x86_64
**Kernel**: 4.17.14-arch1-1-ARCH

**Comment by Lixxia** [comment]
Hey sorry for the delayed response! I'm not super familiar with arch so they may name their packages differently, but I believe you're missing the dev headers for libxkb: libxkbcommon-dev and libxkbcommon-x11-dev. Once these dependencies are resolved it should remove the syntax error, as it'll understand what XCB actually means.
