### ISSUE TITLE
Need help to switch to 24 hours format

### ISSUE THREAD

**Issue by ghost** [Lixxia/i3lock#12]
Hi, 

I'm quite new to Linux and don't know a few things so my question might be a bit dumb.

I want to change the time format to 24 hours.
I found in the file i3lock.c the boolean (set to false by default) and switched it to true and then saved the file.
But my problem is, when I edit the file, it does nothing. (I also tried to switch the colors inside this file but it didn't worked so I used the command line solution)

So what do I have to do to apply the changes made to the file i3lock.c ?

**Comment by Lixxia** [comment]
Hi! These are the source code files and not really meant for changing/configuring values. If you make changes to them you have to recompile everything for it to take effect. That being said, there is an argument on the command line for switching to 24hour format that you should use: ` --24`

**Comment by ghost** [comment]
Thanks !
