### ISSUE TITLE
Out of memory when trying to add a background

### ISSUE THREAD

**Issue by Glorung** [Lixxia/i3lock#7]
Hello,

I got something that went wrong when I'm trying to use your i3lock configuration:

./i3lock -i ./images/background.png -c '#000000' -o '#191d0f' -w '#572020' -l '#ffffff' -e
Could not load image "./images/background.png": out of memory

I don't know what to do with this, and it's not a problem in my memory because I got 8Go of RAM.
(Sorry for my bad english)

**Comment by Lixxia** [comment]
Hi!

Is your background.png truly a png file? If you run `file background.png` what is the output? If it's JPEG then you need to properly convert the image to a png. You can use something like `imagemagick` for that.

Let me know if this solves your issue!

**Comment by orestisfl** [comment]
This is probably a problem from i3lock: https://github.com/i3/i3lock/issues/114
